apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    service: udagram-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-user
  template:
    metadata:
      labels:
        service: udagram-user
    spec:
      containers:
      - name: ducngo1994
        image: ducngo1994/udagram-api-user:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"  
        envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
      restartPolicy: Always